### ISSUE TITLE
errors for locations with a University but no graduates

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1017]
https://wad.datausa.io/profile/geo/tracy-manteca-lathrop-cities-puma-ca#education

**Comment by azapatam** [comment]
**tracy-manteca-lathrop-cities-puma-ca#education** is working :) 

Do you have other examples of small locations to test that the changes applied in that profile are effective in other profiles?

**Comment by azapatam** [comment]
Another thing, I noticed that many N/As arise because `year=latest` is used in the generators... but there are cases where there is data for 2017 and 2018 and `year=latest` "assumes" a `year=2020` and returns no data.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/42551166/203136543-cfc7d358-521f-4bc6-8c62-d19a26304b66.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/42551166/203136563-46abf932-6889-48d8-b08a-0246a481e71e.png">

**Comment by davelandry** [comment]
@azapatam oh no! this is a similar problem to what we started having in PUMS, where certain occupations are not present in the latest year. In that case... we started doing `year=all` in the queries, and manually detecting/extracting the `max` from the payload 😞 

Not the most ideal solution, but we should either hide N/As or use this logic to show previous year's data.
