### ISSUE TITLE
Pulling right year of ACS

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#154]
I am confused as to why New York, the biggest place there is, is using the 5 year estimate. Shouldn't this be a place where we are able to use the 1 or 3 year estimate? http://beta.datausa.io/profile/geo/16000US3651000/#occupations

![image](https://cloud.githubusercontent.com/assets/3857364/12128546/12f7c51e-b3cc-11e5-8552-661bb7172d68.png)

Other places on the same page use the 1 year estimate. Is that just because the occupation stuff isn't provided at the 1 year level?

![image](https://cloud.githubusercontent.com/assets/3857364/12128651/a8ce706a-b3cc-11e5-833e-91a495f6bd57.png)

**Comment by jspeis** [comment]
ACS has discontinued the release of 3-year estimates (there are no 2014 3-year estimates, and when we update the site this Thursday, the ACS data will reflect 2014 data). Also the other place where you saw 1-year data on the page is actually data pulled from the 2014 ACS PUMS 1-year estimate. 

We currently have a rule for national/state data that enables us to pull 1-year data even though the margin of error is higher in the 1-year data (currently we are using the five-year because it has lower margin of error). Similarly, if we prefer the 1-year in "big" places (even when the margin of error represents a larger percent of the value), we could apply a special cut-off that would, for example, allow geographies with population greater than cut off to use the 1-year estimate even if the margin of error is higher (but not all places have data in 1-year estimate, in which case we would only show what we have in the 5-year).

**Comment by danielbyler** [comment]
Ahhh, that makes sense. I think this is a good Patricia question if you want to escalate. We just need to clearly spell this out in some 'about' page. This also seems like a decision that people would waffle back and forth on thereby pointlessly wasting time. Let's batch it with some other items in our next big meeting and get a final decision that's closer to launch. Does that work for you?

**Comment by jspeis** [comment]
I've just added some logic that will let us go either way (based on the data and what is available in terms of 1-year estimates, in the update I've added for now any place with more than 250k people will use 1-year estimates). That threshold can be changed (or completely removed), but thought I would add it sooner rather than later. We will make a note to discuss this in the next big meeting and can re-open the issue as needed

**Comment by danielbyler** [comment]
OK, sounds good. Thanks!
