### ISSUE TITLE
Why is the manufacturing employment number 15 million

### ISSUE THREAD

**Issue by pabucklely** [DataUSA/datausa-site#178]
The actually number is 12 million.

**Comment by danielbyler** [comment]
Here is the BLS citation http://www.bls.gov/iag/tgs/iag31-33.htm

**Comment by jspeis** [comment]
We are using PUMS 2014 data for our estimate. Based on this data, there are an estimated 15M in manufacturing with ~14.1M full-time employees and ~900K part-time employees.

**Comment by pabucklely** [comment]
This is a problem—the standard reference for employment by industry is BLS Current Employment Statistics survey, also known as the “Establishment Survey.”  Not sure why the PUMS has estimates that are so much higher.  Any way to switch?—the site will look wrong otherwise.

Thanks
Patricia

Patricia Buckley
Director | Economic Policy and Analysis
Deloitte Services LP
703 254-3958
pabuckley@deloitte.com | www.deloitte.com

**Comment by danielbyler** [comment]
Maybe we just call them ask why there is a difference, and then put that in the 'about' section of the site with hopefully some good reason as to why we use ACS.

**Comment by alexandersimoes** [comment]
This is definitely an interesting point to bring up here @pabucklely, since there could certainly be people cross checking our data and wondering about this discrepancy. That being said we are too far down the line in the project to incorporate a new dataset. The work that it would require to digest a new dataset, incorporate it into the API and make the relevant front-end changes could potentially delay the project 2 weeks or more. That being said I do see the importance of your point!

I think the best solution is to either add a mouseover saying the specific source of the number or adding a note in the about section mentioning how these 2 datasets diverge.

**Comment by davelandry** [comment]
I've just coded the new CES numbers into the profiles that have them. Here's the Manufacturing page:

<img width="201" alt="screen shot 2016-02-10 at 5 53 32 pm" src="https://cloud.githubusercontent.com/assets/1847581/12964642/487c5f82-d01f-11e5-9544-27b6126c6a0c.png">

And here's a page that does not have data in the CES dataset:

<img width="210" alt="screen shot 2016-02-10 at 5 53 01 pm" src="https://cloud.githubusercontent.com/assets/1847581/12964659/59280408-d01f-11e5-89ce-cb180ac65037.png">
