### ISSUE TITLE
map control improvements

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#186]
##marking as suggestion

Suggest enabling zoom controls on scroll and ctrl+left click to draw zooming bounding boxes. Will make navigating around quicker. Otherwise suggest increasing size of plus minus.

**Comment by davelandry** [comment]
Great suggestions. We disabled scroll zoom because it awkwardly conflicts with scrolling through profile pages, but we should enable it on the full-screen page. Zooming by bounding box is a little trickier (more work), but still a good idea.
- [ ] enable scroll zoom on full-screen page
- [ ] increase effect of plus/minus buttons
- [ ] zoom by drawing bounding area

**Comment by davelandry** [comment]
Just put in bounding box zooming while holding shift (more consistent cross-OS than ctrl). I think this alleviates the need to increase the effect of plus/minus buttons.
