### ISSUE TITLE
confusion with selected geo popup and hover popup

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#234]
The popup on the map of wages by location does not go away once you refresh the map.  I will send Dave a screenshot by email.

-Peter

**Comment by davelandry** [comment]
Here's the screenshot in question:
![image003](https://cloud.githubusercontent.com/assets/1847581/13295150/73951fac-daf5-11e5-9b39-4384a66f6120.jpg)

@pviechnicki the tooltip on the top right is for the geography that was clicked and centered on ("last selected geography" in the tooltip), and the other tooltip only appears for new geographies that you manually hover over. Do you have a suggestions for expected behavior here? We want to have that selected tooltip, as it allows potentially showing more information than the hover tooltip and you can click on the title to go to that profile page. I will say though, that this does work better on larger screens, so maybe it only appears on screens where it won't take up half of the map?
