### ISSUE TITLE
out of date occupational projections

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#294]
I'm doing a story on fast growing jobs. The BLS list of fastest growing jobs is here http://www.bls.gov/ooh/fastest-growing.htm . I can't find a good match for the wind turbine people and the growth rate given for occupational therapists is lower in our data than in the BLS data http://beta.datausa.io/profile/soc/312010/ . Have they pushed an updated dataset while we've been in development? http://beta.datausa.io/profile/soc/4990XX/ was my guess for mapping to the wind turbines but its growth rate is nothing like the growth rate in the BLS link I found. 

Are we using different data or was this a big update in their latest data?

**Comment by davelandry** [comment]
@jspeis will be able to speak the most knowledgeably about this, but my guess would be that the discrepancy might lie in the BLS using their own custom SOC codes, and our site having to map these codes using a crosswalk to our standardized SOC equivalent for profiles.

**Comment by jspeis** [comment]
1. The BLS data updated their data after we completed our data ingestion phase. 

It doesn't seem like BLS keeps an easy to access time-series view of this data but you can see our source from the internet archive: https://web.archive.org/web/20150905075605/http://www.bls.gov/emp/ep_table_102.htm

2. Note that there is a difference in classification between "**Occupational Therapists**" (291122) and "**Occupational Therapy Assistants & Aides**" (312010) --- not sure if this may have been a confounding factor?

3. Since PUMS does not match 1:1 with the wind turbine service technicians, the closest page on our platform would be its parent: http://beta.datausa.io/profile/soc/490000/

**Comment by danielbyler** [comment]
Are you going to update the data prior to launch? This is a big jump since it's a 2 year gap in the data.

**Comment by jspeis** [comment]
It is too late in the process for data updates, but if there is an issue we can remove the effected section.

**Comment by danielbyler** [comment]
Separate/related- I do have one question though. Could you double check that the 'national average' is correct? The number of 2014 is like 7-8% and it would have been a big revision for BLS to downgrade its labor force growth rate that much after 2 years. Granted it hasn't been a super great two years for the labor market but I'd just like a two second double check. 

Thanks!

**Comment by jspeis** [comment]
![screen shot 2016-03-14 at 4 12 47 pm](https://cloud.githubusercontent.com/assets/87581/13758396/a8782412-e9ff-11e5-9819-a32088fc9d0d.png)

**Comment by danielbyler** [comment]
Fair enough! Thanks.

**Comment by jspeis** [comment]
BLS projections now reflect 2014-2024 data
