### ISSUE TITLE
add logo and source elements to PDFs and PNGs

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#352]
On this profile, when I choose options->download->image, I get an image with black boxes instead of legend entries, plus there's no DataUSA logo.  I thought the logo was supposed to appear on exports/embeds in this release.  The legend export will need to be improved.  You'll need to put colored and labeled boxes.  The images with pop-ups won't work for the exports.

**Comment by davelandry** [comment]
The issue with the legend is documented here: #262 

The DataUSA logo does appear in embedded visualizations, as seen in [this link](http://beta.datausa.io/profile/geo/flint-mi/economy/poverty_ethnicity/). My understanding from the call where we discussed it was that we specifically didn't want the logo appearing in all file exports, but only on the web with a link back to the site.

**Comment by davelandry** [comment]
I'm upgrading this from a question to a feature. We should include the data source and the site logo on all image/pdf downloads.

That being said, this is not an easy task, as the current rendering engine we use to generate the downloads only ingest the visualization itself. We will have to write custom code to also grab the source, along with rendering the logo on the fly (because it does not appear on the profile pages).
