### ISSUE TITLE
MSA names appear to be out of date in API - using wrong standard?

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#390]
I'm pulling the MSA names from the API using this call:

var url2 = "http://api.datausa.io/attrs/geo/?sumlevel=msa";

What I get appears to be out of date (2009 vintage, not 2013 vintage).  For example, the name of the Denver MSA in the current datausa is 'Denver-Aurora-Bloomfield' but it should be 'Denver-Aurora-Lakewood.'  Similar issue with Baltimore.  The 2013 standard has 'Baltimore-Columbia-Towson', but the datausa api gives 'Baltimore-Towson.'

Here is a document which looks pretty official and tells you the differences between the 2009 and 2013 standards.  We need to get to the current one.

http://www.fhfa.gov/datatools/downloads/documents/hpi_focus_pieces/2013q2_hpifocus_n508.pdf
Thanks,
-Peter

**Comment by jspeis** [comment]
This should be fixed in the next release:

![screen shot 2016-05-02 at 4 41 25 pm](https://cloud.githubusercontent.com/assets/87581/14967344/d2c54190-1084-11e6-9b7a-0cf4a111e76d.png)
![screen shot 2016-05-02 at 4 41 02 pm](https://cloud.githubusercontent.com/assets/87581/14967348/d87d4a1a-1084-11e6-843c-ed0e7dbb50b9.png)
