### ISSUE TITLE
Zoom not working properly on map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#395]
Shift-drag doesn't appear to work on this map, and clicking once zooms all the way in:

http://datausa.io/profile/soc/171020/#locations

**Comment by davelandry** [comment]
Everything seems to work for me. I've tested in Chrome, Firefox, IE, and Safari.

@pviechnicki can you describe what is happening and what browser/os you are using? Expected behavior is that clicking on a location will zoom to that location, and holding shift allows you to click and drag a bounding box to zoom to.

**Comment by pviechnicki** [comment]
I just tried to replicate this in both chrome and firefox and it appears to work fine in both.  I think you can close this one.

**Comment by davelandry** [comment]
👍
