### ISSUE TITLE
MIssing autotext for poverty by race chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#533]
Reference this chart:
http://sunbird.datausa.io/profile/geo/phoenix-az/#category_wages

There is nothing listed under the text for the top three.  This is confusing.  Either change the autotext or put the information back in.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki the link you posted is for the overall "Wages" section. I believe you are referring to this chart? http://sunbird.datausa.io/profile/geo/phoenix-az/#poverty_ethnicity

In order to get the link for a specific chart, you need to click on the title for the chart, in this case "Poverty by Race & Ethnicity".

That being said, I'm unable to reproduce this bug. Please check if you are still seeing this, and if so, update the original post with your browser and OS.

**Comment by davelandry** [comment]
Deprecated in 3.0
