### ISSUE TITLE
all single parents in loving county?

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#560]
https://datausa.io/map/?level=county&key=children_in_singleparent_households 

Can you just check that there are 0 people in a 2 parent household in Loving County, TX https://datausa.io/map/?level=county&key=children_in_singleparent_households ?

**Comment by davelandry** [comment]
Going back to the data source, 100% of households in Loving County are single parent households: http://www.countyhealthrankings.org/app/texas/2017/rankings/loving/county/factors/4/snapshot

Turns out, Loving County is the smallest county in the US (from Wikipedia):
> With a population of 82 as of the 2010 census, Loving County is the least populated county in the United States. Loving County has no incorporated communities

The data source also lists the margin of error at 0-100%... so I think this is a good case for getting those error rates in the front-end (#527)
