### ISSUE TITLE
show CHR source year(s) in tooltips and color scale

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#573]
The 'Ranked Measure Sources and Years Tab' and the 'Addtln Measure Sources and Years' tab of the 2017 County Health Rankings show that the date of information of the drug overdose deaths is 2013-2015.  We're showing 2017.  Need to fix the years for all variables in this data source.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Talked with @jspeis about this, and it looks like there are 3 different situations we run into for each individual CHR variable:
1. data comes from a single year (ie. 2015)
2. data comes from a range of years (ie. 2013-2015)
3. data comes from 2 distinct years (ie. 2013 & 2015)

In order to avoid completely re-writing some of the underlying database structure, we'd like to propose continuing to use the publishing year as the main "year" field in the database and show an explicit warning in the tooltips and legends that explicitly states the year(s) the data has been collected from. @pviechnicki what do you think?

**Comment by davelandry** [comment]
Collection year(s) now appears in all viz tooltips. I chose not to put it in the legend, as it became a little crowded and confusing given the timeline being there as well.
