### ISSUE TITLE
3rd level selector on map page

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#594]
- [ ] Race Selection for Dartmouth Atlas Black/Non-Black Variables
  - Diabetic care
  - LIpid Tests
  - Leg Amputations
  - etc...
- [ ] Languages Spoken

**Comment by davelandry** [comment]
Adding a 3rd level of hierarchy to the map page is a non-trivial feature, so I'm converting this issue into a larger feature request to accommodate this. We've had this requested for multiple items, so I think this should be high on the priority list for post-launch.

I will be updating the original post here with requests as they come in so that when we do hook this up, we make sure we hit every side of it.

**Comment by davelandry** [comment]
Available in the new viz builder!
