### ISSUE TITLE
set up nightly backups of mortar db on server

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#717]
identical to the cron job on the codelife server

**Comment by jspeis** [comment]
@jhmullen it would be nice if we can have it so that backups get copied to a google cloud bucket. There's a tool called `gsutil` than basically can be used to copy files from a server to a cloud bucket (so this way we can retain backups longer and not have to worry about filling up the server).

Feel free to create a new folder in our [existing cloud storage bucket](https://console.cloud.google.com/storage/browser/datausa-storage.datawheel.us/?project=data-usa-174910&authuser=1&organizationId=472157795465) to store the canon frontend DB backups. (we'll want to separate that from the existing datausa_db folder which holds a backup of the last version of the live Data USA db for the current datausa.io).

[See this link for more info](https://cloud.google.com/storage/docs/gsutil_install)

[This script](https://gist.github.com/studiotomi/231c321ba2a2abf41b7cba02c568f7a5) also seems to have a reasonable example of how that can work. So the gs bucket path work look something like `gs://datausa-storage.datawheel.us/<name of the backups folder here>/`

**Comment by jhmullen** [comment]
There is now a `backup_db.sh` that lives in HOME on canon. This creates a tarball and uploads it to our google cloud server. It is set to run at `0 4 * * *` in crontab. Just awaiting a code review from @davelandry in slack and i'll mark this as complete.
