### ISSUE TITLE
review University and CIP parent stats in CMS

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#765]
I just pushed an update to the preview lists to include University and CIP parent groupings (ie. "Doctoral Universities"). There are some N/As appearing in the Carnegie groups, so please check both profiles (starting tomorrow 11/16 on `katahdin.datausa.io`)

**Comment by jhmullen** [comment]
@davelandry The following "Default Rate" query on the university page is failing for Carnegies and Carnegie Parents:

`/api/data?OPEID=<id>&measures=Default%20Rate,Borrowers%20In%20Default,Borrowers%20Entered%20Repayment&Year=latest`

I believe the Default Rate relies on your [https://github.com/DataUSA/datausa-site/blob/canon/api/crosswalks.js#L114](OPEID crosswalk), does anything special need to be done for this crosswalk to work with Carnegies and Parents?

**Comment by jspeis** [comment]
@jhmullen because of differences between OPEID6 and university (an OPEID can correspond to universities with different Carnegie groups) and since the default rate data is only available in OPEID6 format - the carnegie level data for the default rate is not available (eg you see N/A for the default rate in the live site on Carnegie pages as well: https://datausa.io/profile/university/doctoral-universities/)

**Comment by jhmullen** [comment]
Thanks @jspeis I've added some code to the Default Rate Generator that makes this fail slightly more gracefully.

**Comment by jhmullen** [comment]
Yes, I added a better lookup to clear the N/As and carlos is auditing the results.
