### ISSUE TITLE
Is this actually time series data?

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#771]
https://joshua-tree.datausa.io/visualize?groups=0-z7J78&measure=Z1hS30j

I think this chart is making up a start year when there is only one year of data but I am not sure about that and wanted to flag it 

![image](https://user-images.githubusercontent.com/3857364/49228713-f170c900-f3b9-11e8-9ea7-ef867a5f4357.png)

**Comment by davelandry** [comment]
I believe this is a known artifact in the County Health Rankings dataset. We show the data they publish each year, but some indicators in some years do not get updated because they haven't collected new data for them (but they still publish them with everything else).

I'll wait on @jspeis to confirm before closing this.

**Comment by jspeis** [comment]
can confirm that 2014 & 2015 CHR data both use the same underlying data of BRFSS 2006-2012:

<img width="772" alt="screen shot 2018-12-06 at 8 55 06 am" src="https://user-images.githubusercontent.com/87581/49588500-d9a6c100-f934-11e8-8890-977b1ff758ca.png">

<img width="731" alt="screen shot 2018-12-06 at 8 56 55 am 2" src="https://user-images.githubusercontent.com/87581/49588554-02c75180-f935-11e8-8491-91e965a140f8.png">
